"""Writer Agent - Synthesizes research findings into a professional report.

This agent takes all verified facts, sources, and raw findings to
produce a comprehensive, well-structured research report in Markdown.
"""

import time
from src.config import get_llm
from src.state import ResearchState


WRITER_PROMPT = """You are a Professional Research Report Writer. Write a comprehensive, well-structured
research report based on the verified facts and sources provided.

Original Research Question: {query}

=== Verified Facts (with confidence levels) ===
{verified_facts}

=== Sources Used ===
{sources}

Write a professional research report in Markdown format with these EXACT sections:

# Research Report: {query}

## Executive Summary
Write a 2-3 paragraph overview of the key findings. Be concise but comprehensive.

## Key Findings
List the most important findings as bullet points. For each finding, include a confidence badge:
- Use [HIGH] for high confidence facts
- Use [MEDIUM] for medium confidence facts  
- Use [LOW] for low confidence facts

## Detailed Analysis
Provide in-depth analysis organized by theme or subtopic. Use subheadings (###) to organize.
Reference specific sources when making claims.

## Academic Insights
If academic papers were referenced, summarize the key academic contributions.
If no papers were found, write "No academic papers were found for this specific query."

## Sources & Citations
List all sources used with their URLs as numbered references.
Format: 1. [Source Name](URL)

## Confidence Assessment
Summarize the overall reliability of the findings:
- How many sources were consulted
- How many facts were high/medium/low confidence
- Any notable contradictions or gaps in the research

---
*Report generated by DeepResearch AI*

IMPORTANT: Write in a professional, academic tone. Be factual and cite sources. The report should
be 800-1500 words long. Use proper Markdown formatting throughout."""


def writer_node(state):
    """Synthesize all research into a professional report."""
    query = state.get("query", "")
    verified_facts = state.get("verified_facts", [])
    sources = state.get("sources", [])

    print(f"\n{'='*60}")
    print(f"WRITER AGENT: Synthesizing report from {len(verified_facts)} facts...")
    print(f"{'='*60}\n")

    # Pace between agents
    print("  >> Pacing: waiting 5s before writing report...")
    time.sleep(5)

    facts_text = _format_verified_facts(verified_facts)
    sources_text = _format_sources(sources)

    try:
        llm = get_llm(temperature=0.3)
        response = llm.invoke(WRITER_PROMPT.format(
            query=query,
            verified_facts=facts_text,
            sources=sources_text
        ))

        report = response.content.strip()
        print(f"  Report generated: {len(report)} characters")

    except Exception as e:
        print(f"  Writer error: {e}")
        report = _create_fallback_report(query, verified_facts, sources)

    return {
        "final_report": report,
        "status_updates": [
            "Writer: Research report complete"
        ],
    }


def _format_verified_facts(facts):
    if not facts:
        return "No verified facts available."
    parts = []
    for i, fact in enumerate(facts, 1):
        confidence = fact.get("confidence", "MEDIUM")
        claim = fact.get("claim", "N/A")
        sources = ", ".join(fact.get("supporting_sources", []))
        contradictions = fact.get("contradictions", [])
        text = f"{i}. [{confidence}] {claim}\n   Sources: {sources}"
        if contradictions and any(c for c in contradictions if c):
            text += f"\n   Contradictions: {', '.join(str(c) for c in contradictions if c)}"
        parts.append(text)
    return "\n\n".join(parts)


def _format_sources(sources):
    if not sources:
        return "No sources available."
    seen_urls = set()
    unique_sources = []
    for s in sources:
        url = s.get("url", "")
        if url and url not in seen_urls:
            seen_urls.add(url)
            unique_sources.append(s)
        elif not url:
            unique_sources.append(s)
    parts = []
    for i, s in enumerate(unique_sources, 1):
        source_type = s.get("source_type", "web").upper()
        name = s.get("source", "Unknown")
        url = s.get("url", "N/A")
        parts.append(f"{i}. [{source_type}] {name} - {url}")
    return "\n".join(parts)


def _create_fallback_report(query, facts, sources):
    report = f"# Research Report: {query}\n\n"
    report += "## Executive Summary\n\n"
    report += f"This report presents findings on the topic: {query}.\n\n"
    report += "## Key Findings\n\n"
    for fact in facts[:10]:
        claim = fact.get("claim", "")
        confidence = fact.get("confidence", "MEDIUM")
        report += f"- [{confidence}] {claim}\n"
    report += "\n## Sources & Citations\n\n"
    for i, s in enumerate(sources[:10], 1):
        name = s.get("source", "Unknown")
        url = s.get("url", "")
        report += f"{i}. {name} - {url}\n"
    report += "\n---\n*Report generated by DeepResearch AI*\n"
    return report
